services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-invites}
      POSTGRES_USER: ${POSTGRES_USER:-invites}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-invites}
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER:-invites}", "-d", "${POSTGRES_DB:-invites}" ]
      interval: 10s
      timeout: 3s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - invites_keycloak_network

  app:
    image: hu553in/invites-keycloak:local
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE:-prod}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-invites}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-invites}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-invites}
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8080/actuator/health", "|", "grep", "UP", "||", "exit", "1" ]
      interval: 10s
      timeout: 3s
      retries: 10
    depends_on:
      db:
        condition: service_healthy
    networks:
      - invites_keycloak_network

volumes:
  db_data:

networks:
  invites_keycloak_network:
