processors:
  active: true

config:
  validation: true

formatting:
  active: true
  android: false
  PackageName:
    active: false

naming:
  PackageNaming:
    active: false

complexity:
  LongParameterList:
    active: false
  NamedArguments:
    active: true
  TooManyFunctions:
    active: false

style:
  MagicNumber:
    ignoreAnnotation: true
  BracesOnIfStatements:
    active: true
    singleLine: always
